name: leksis
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  shared_preferences: ^2.5.2
  google_fonts: ^6.2.1
  sqflite: ^2.4.2
  path: ^1.9.1
  draggable_fab: ^0.1.4
  fluttertoast: ^8.2.12
  swipeable_card_stack: ^0.0.5
  flash_card: ^0.1.0
  share_plus: ^10.1.4
  file_picker: ^9.2.1
  excel: ^4.0.6
  path_provider: ^2.1.5
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
